### ISSUE TITLE
Pick up venv from nvim environment

### ISSUE THREAD

**Issue by gwenwindflower** [phdah/nvim-databricks#10]
Really, really neat plugin! Thank you for your hard work on this! 💗✨

One thing I noticed getting it to work last night is that it doesn't seem to pick up the venv from nvim's environment? I often launch into nvim and then use [venv-selector.nvim](https://github.com/linux-cultist/venv-selector.nvim) to select a venv. I had to explicitly quit nvim and activate a venv in my shell, and then come back in for it to pick up `databricks-connect`.

More than anything just wanted to say great work on this though, really working well for me. Thanks!

**Comment by phdah** [comment]
Thanks for your question @gwenwindflower. So as of now, the `python interpreter` is used fairly _naively_ here. Simply the interpreted set in the table passed to the `setup` function, see `README`, is directly used. So the defult:
```lua
require('nvim-databricks').setup({
    ...
    python = 'python3.10', -- Set Python version for DBRun
})
```
and running `DBRun`, will actually just run the file as
```bash
python3.10 your_awesome_file.py [args]
```
What have you specified in the `setup` config, and how would you typically run a python file after have specified the `.venv` using the [venv-selector.nvim](https://github.com/linux-cultist/venv-selector.nvim) plugin?

**Comment by phdah** [comment]
Looking into the specific [venv-selector.nvim](https://github.com/linux-cultist/venv-selector.nvim) plugin, you should be able to just set the `python` variable in `setup` to be `python = require('venv-selector').get_active_path()`? If it's not already possible, I can look into enabling the config to allow for a lua function, making the above possible.

Please confirm if this is how one would use the [venv-selector.nvim](https://github.com/linux-cultist/venv-selector.nvim) to run a python file.

**Comment by gwenwindflower** [comment]
ah okay, that makes sense, thank you for explaining. i shot a short video showing how i typically use this plugin, basically it just seems to update some sort of internal working state/temporary PATH in nvim that other plugins (LSPs, linters, terminals, etc) seem to pick up. So I made (very likely wrong) assumption that such a thing exists in the context of Neovim and could be easily hooked into. so to answer your question directly, i just run a python file normally. Makes sense how this plugin is handling this though, I'll think about how I could figure this out and make it happen, thanks! I'll close the issue, don't think this requires anything on your end.

https://github.com/phdah/nvim-databricks/assets/91998347/504fd811-76c6-4cb4-b033-3c6836e8f5de

**Comment by phdah** [comment]
@gwenwindflower, please reference to this PR https://github.com/phdah/nvim-databricks/pull/11, where the default `python interpreter` is updated, as well as a reference explicitly to the venv plugin for how to set it up. I think both those things will make it work as you intend.

**Comment by gwenwindflower** [comment]
@phdah awesome! thanks for the quick response 💗.

**Comment by gwenwindflower** [comment]
also tiny tip i've learned from my own gh projects: you can create nicely formatted admonitions for callouts like this —

> [!NOTE]
> My stuff in my note

```
> [!NOTE]
> My stuff in my note
```

works with (NOTE|WARNING|IMPORTANT|TIP) all with different colors/formatting.
